# When converting this project to TS I had all the package dependencies installed and all the files with the ts 
# extension yet I was getting type errors. AI wasn't helping me figure it out. When looking into the tsconfig files
# I noticed in the tsBuildInfoFile property that it referenced the node_modules directory. But since I was using the
# latest yarn version which doesn't create a node_modules directory, typing was never working. The solution was to 
# create this file and add the following line to instruct yarn to create the node_modules which resolved the typing error
nodeLinker: node-modules